spring.application.name=task-api
spring.datasource.url=jdbc:postgresql://localhost:5432/task_api
spring.datasource.username=postgres
spring.datasource.password=03042001aA@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true